version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: ./simple-python-app/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./simple-python-app/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./simple-python-app/start_container.sh
      timeout: 300
      runas: root
